### ISSUE TITLE
Gradle can't generate decorated class for ScalafixPlugin

### ISSUE THREAD

**Issue by blondacz** [cosmicsilence/gradle-scalafix#25]
Following error is produced by gradle (6.5) when applying the plugin (0.1.2):
```
> Failed to apply plugin [id 'io.github.cosmicsilence.scalafix']
   > Could not create plugin of type 'ScalafixPlugin'.
      > Could not generate a decorated class for class io.github.cosmicsilence.scalafix.ScalafixPlugin.
         > scalafix/interfaces/ScalafixMainMode
...

Staktrace shows:
```
...
Caused by: java.lang.NoClassDefFoundError: scalafix/interfaces/ScalafixMainMode
        at org.gradle.internal.reflect.ClassInspector.inspectClass(ClassInspector.java:69)
        at org.gradle.internal.reflect.ClassInspector.visitGraph(ClassInspector.java:55)
        at org.gradle.internal.reflect.ClassInspector.inspect(ClassInspector.java:35)
        at org.gradle.internal.instantiation.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:245)
        at org.gradle.internal.instantiation.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:191)
        ... 210 more
Caused by: java.lang.ClassNotFoundException: scalafix.interfaces.ScalafixMainMode
        ... 215 more
```

**Comment by marcelocenerine** [comment]
@blondacz thanks for reporting this issue. I'm unable to reproduce this issue using Gradle 6.5. Our [functional tests](https://github.com/cosmicsilence/gradle-scalafix/blob/master/src/compatTest/groovy/io/github/cosmicsilence/scalafix/ScalafixPluginFunctionalTest.groovy) are now running against [Gradle 6.5 ](https://github.com/cosmicsilence/gradle-scalafix/blob/master/.stutter/java8.lock#L5) and they all pass. I also set up a dummy project but not luck.

Do you have a repo that I could clone?

**Comment by marcelocenerine** [comment]
Please reopen if the error persists after upgrading to the latest version
